site_name: SyncrnzdClk's Notebook
theme:
  name: material
  features:
    - navigation.instant
nav:
  - HomePage: index.md
  - abstract_algebra: 
    - pre: abstract_algebra/pre.md
    - abstract algebra: abstract_algebra/abstract algebra.md 
  - convex optimization: 
    - pre: convex optimization/pre.md
    - convex optimization: convex optimization/notes/convex sets and functions.md