site_name: SyncrnzdClk's Notebook
theme:
  name: material
  features:
    - navigation.instant
nav:
  - HomePage: index.md
  - abstract_algebra: 
    - pre: abstract_algebra/pre.md
    - notes: 
      - preliminaries and integers: abstract_algebra\notes\preliminaries.md
  - convex optimization: 
    - pre: convex optimization/pre.md
    - notes: 
      - convex sets and functions: convex optimization/notes/convex sets and functions.md